-- =============================================================================
-- Supabase Storage: print-files bucket
-- =============================================================================
--
-- Bucket name : print-files
-- Access      : private (public = false) — Requirement 9.1
--               No public URLs are ever issued for this bucket.
--
-- File path convention
--   jobs/{job_id}/{sanitized_filename}.pdf
--
--   job_id            — UUID of the print_jobs row (links file to DB record)
--   sanitized_filename — result of sanitizeFilename() from lib/filename.ts
--                        (alphanumeric, hyphens, underscores only; ≤ 100 chars base; .pdf suffix)
--
-- URL expiry policy (Requirement 9.2)
--   Signed upload URL  : 2 hours  (generated by /api/create-job for browser upload)
--   Signed download URL: 60 minutes (generated by /api/signed-url for web preview)
--
-- Print Controller access (Requirement 9.3)
--   The print controller downloads files directly via Service_Role_Key using:
--   supabase.storage.from_('print-files').download(file_path)
--   The Service_Role_Key is never exposed to the frontend (Requirement 9.4).
--
-- RLS note
--   storage.objects RLS is enforced by Supabase's storage engine.
--   Anon users interact with this bucket exclusively via short-lived signed URLs.
--   The service_role bypasses RLS and has full access by default.
-- =============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('print-files', 'print-files', false)
ON CONFLICT (id) DO NOTHING;
